### ISSUE TITLE
Не раскрывается поле для ввода текста поиска на моб версии

### ISSUE THREAD

**Issue by LubaPM** [MalahVitalij/rocket-mosdiplom#26]
http://joxi.ru/DmBPD9qTwlzZYA

**Comment by VladyslavKovalchuk** [comment]
сделать, чтоб выезжало сбоку и становилось вместо значка http://prntscr.com/l70nlb

**Comment by VladyslavKovalchuk** [comment]
в мобильной нужно добавить кнопку для поиска, когда поле открыто, можно использовать ту же иконку в правом краю этого поля, только сделать ей цвет

**Comment by VladyslavKovalchuk** [comment]
в фф и опере не срабатывает добавленная кнопка на телефоне
